// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lskhvpstseyoabgheoka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxza2h2cHN0c2V5b2FiZ2hlb2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNjAxMzIsImV4cCI6MjA1NDgzNjEzMn0.RxFNS9yFj8G297RhvFW_QP72K3kUxo0rBsl8t_PiOGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);